name: medfuse
channels:
  - pytorch
  - nvidia
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.2.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.2.1
  - blinker=1.4
  - bravado=11.0.3
  - bravado-core=5.17.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.7.5
  - cairo=1.14.12
  - certifi=2021.5.30
  - cffi=1.14.3
  - chardet=3.0.4
  - click=8.0.1
  - cloudpickle=1.6.0
  - cryptography=3.1.1
  - cudatoolkit=11.1.74
  - cycler=0.10.0
  - dataclasses=0.8
  - dbus=1.13.6
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.9
  - ffmpeg=4.0
  - fontconfig=2.13.1
  - freeglut=3.0.0
  - freetype=2.10.4
  - future=0.18.2
  - gitdb=4.0.7
  - gitpython=3.1.18
  - glib=2.66.1
  - graphite2=1.3.14
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.8.0
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - icu=58.2
  - idna=2.10
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jasper=2.0.14
  - jedi=0.17.2
  - jinja2=2.11.2
  - joblib=0.17.0
  - jpeg=9b
  - jsonref=0.2
  - jsonschema=3.2.0
  - jupyter_client=6.1.7
  - jupyter_core=4.6.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - keras=2.1.2
  - kiwisolver=1.3.1
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libglu=9.0.0
  - libopencv=3.4.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libprotobuf=3.17.2
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libuv=1.40.0
  - libvpx=1.7.0
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib=3.3.3
  - matplotlib-base=3.3.3
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - mock=4.0.3
  - monotonic=1.5
  - msgpack-python=1.0.2
  - nb_conda=2.2.1
  - nb_conda_kernels=2.3.0
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - ncurses=6.2
  - neptune-client=0.10.8
  - nest-asyncio=1.4.1
  - networkx=2.5
  - ninja=1.10.2
  - notebook=6.1.4
  - numpy=1.19.2
  - numpy-base=1.19.2
  - oauthlib=3.0.0
  - olefile=0.46
  - opencv=3.4.2
  - openssl=1.1.1l
  - packaging=20.4
  - pandas=0.23.4
  - pandoc=2.11
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.0.0
  - pip=20.3.3
  - pixman=0.40.0
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.8
  - protobuf=3.17.2
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - py-opencv=3.4.2
  - py3nvml=0.2.5
  - pycparser=2.20
  - pygments=2.7.1
  - pyjwt=1.7.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.6.12
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytorch=1.9.0
  - pytz=2020.1
  - pyyaml=5.4.1
  - pyzmq=19.0.2
  - qt=5.9.7
  - readline=8.0
  - requests=2.24.0
  - requests-oauthlib=1.3.0
  - scikit-learn=0.24.2
  - scipy=1.5.2
  - send2trash=1.5.0
  - setuptools=51.0.0
  - simplejson=3.17.3
  - sip=4.19.8
  - six=1.15.0
  - smmap=4.0.0
  - sqlite=3.33.0
  - swagger-spec-validator=2.7.3
  - tensorflow=1.1.0
  - terminado=0.9.1
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - torchaudio=0.9.0
  - torchvision=0.2.2
  - tornado=6.0.4
  - tqdm=4.55.1
  - traitlets=4.3.3
  - typing-extensions=3.10.0.0
  - typing_extensions=3.10.0.0
  - urllib3=1.25.11
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - werkzeug=1.0.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - xmltodict=0.12.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.3
  - zipp=3.3.1
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - fuzzywuzzy==0.18.0
    - warmup-scheduler==0.3.2
